// Codegen: packages/shared/schema/events/*.schema.json -> TS zod validators + types.
// Single source of truth = the JSON Schema. Python pydantic models are generated
// separately by datamodel-code-generator (see infra/scripts or CI api job).
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { jsonSchemaToZod } from "json-schema-to-zod";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const schemaDir = join(root, "packages/shared/schema/events");
const outDir = join(root, "packages/shared/ts/generated");
mkdirSync(outDir, { recursive: true });

const files = readdirSync(schemaDir)
  .filter((f) => f.endsWith(".schema.json"))
  .sort();

const entries = [];
for (const file of files) {
  const schema = JSON.parse(readFileSync(join(schemaDir, file), "utf8"));
  const title = schema.title; // PascalCase, e.g. GoalCreated
  const constName = title[0].toLowerCase() + title.slice(1) + "Schema";
  const base = file.replace(".schema.json", "");
  const body = jsonSchemaToZod(schema, { module: "esm", name: constName, type: title });
  writeFileSync(join(outDir, `${base}.ts`), `${body}\n`);
  entries.push({ base, constName, title });
}

const constants = JSON.parse(
  readFileSync(join(root, "packages/shared/schema/constants.json"), "utf8"),
);

let index = "// GENERATED by scripts/codegen.mjs — do not edit by hand.\n";
index += entries
  .map((e) => `export { ${e.constName}, type ${e.title} } from "./${e.base}.js";`)
  .join("\n");
index += `\n\nexport const EVENT_TYPES = ${JSON.stringify(
  constants.eventTypes,
  null,
  2,
)} as const;\n`;
index += "export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];\n";
writeFileSync(join(outDir, "index.ts"), index);

console.log(`[codegen] wrote ${entries.length} zod modules to packages/shared/ts/generated`);
